# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chapel Hill Friends Meeting
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chapelhillfriends.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chfm_quakers
github_username:  chfm

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  - forums
  - currently

# tipuesearch config
tipue_search:
  include:
    pages: true
    collections: [apples, oranges]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

defaults:
  - scope:
      path: "nl/2020"
    values:
      nl_year: 2020
      newsletter: true
  - scope:
      path: "nl/newsletter-2019*.pdf"
    values:
       nl_year: 2019
       newsletter: true
  - scope:
      path: "nl/newsletter-2018*.pdf"
    values:
       nl_year: 2018
       newsletter: true
  - scope:
      path: "nl/newsletter-2017*.pdf"
    values:
       nl_year: 2017
       newsletter: true
  - scope:
      path: "nl/newsletter-2016*.pdf"
    values:
      nl_year: 2016
      newsletter: true
  - scope:
      path: "nl/newsletter-2015*.pdf"
    values:
      nl_year: 2015
      newsletter: true
  - scope:
      path: "nl/newsletter-2014*.pdf"
    values:
      nl_year: 2014
      newsletter: true
  - scope:
      path: "nl/newsletter-2013*.pdf"
    values:
      nl_year: 2013
      newsletter: true
  - scope:
      path: "nl/newsletter-2012*.pdf"
    values:
      nl_year: 2012
      newsletter: true
  - scope:
      path: "nl/newsletter-2011*.pdf"
    values:
      nl_year: 2011
      newsletter: true
  - scope:
      path: "nl/newsletter-2010*.pdf"
    values:
      nl_year: 2010
      newsletter: true
  - scope:
      path: "nl/newsletter-2009*.pdf"
    values:
      nl_year: 2009
      newsletter: true
  - scope:
      path: "nl/newsletter-2008*.pdf"
    values:
      nl_year: 2008
      newsletter: true
